#!/bin/sh
set -e

# run scripts in DIR
DIR=/docker-entrypoint.d
if [ -d "$DIR" ]; then
  /bin/run-parts --verbose "$DIR"
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
